[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts', '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts', '@chainlink/contracts/=node_modules/@chainlink/contracts',
'@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip','@solmate/contracts=lib/solmate/src', '@hyperlane-xyz/=node_modules/@hyperlane-xyz/']
ffi = true
solc-version = "0.8.20" 
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
